dist: xenial
language: ruby
cache:
  bundler: true
  yarn: true
  directories:
    - node_modules
sudo: required
bundler_args: --without production
before_install:
  - gem update --system
  - gem install bundler --pre
  - nvm install node
  - npm i -g yarn
install:
  - bundle install --jobs=3 --retry=3
  - yarn install --frozen-lock
before_script:
  - bin/bundle exec bin/travis
script:
  - yarn lint
  - yarn jest
  - rake ci
rvm:
  - 2.5.8
jdk:
  - openjdk8
addons:
  apt:
    packages:
      - dpkg # fix for travis issue https://github.com/travis-ci/travis-ci/issues/9361
      - qpdf
  chrome: stable
services:
  - mysql
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
